<?php 
 $title = 'Search Album';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <?php
 $form->setAttribute('action', $this->url('album', array('action' => 'search')));
 $form->prepare();

echo $this->form()->openTag($form);
foreach ($form as $element) {
echo $this->formElement($element);       
echo $this->formElementErrors($element);
}
echo $this->form()->closeTag();

?>
 <table class="table">
 <tr>
     <th>Title</th>
     <th>Artist</th>
     <th>File</th>
 </tr>
 <?php foreach ($results as $result) : ?>
 <tr>
     <td><?php echo $this->escapeHtml($result->title);?></td>
     <td><?php echo $this->escapeHtml($result->artist);?></td>
      <td><a href="<?php echo $this->escapeHtml($this->url('users/upload-manager',
            array('action'=>'fileDownload', 'id' => $searchResult->upload_id)));?>">Download</a></td>
 </tr>
 <?php endforeach; ?>
 </table>

